cookie:
  expiry_days: 30
  key: c0e4178ecf852c7b9cf9934f2fe6d490
  name: work_doc_auth
credentials:
  usernames:
    shiro1729:
      email: a0416517630@icloud.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: MW
      last_name: ""
      logged_in: False # Will be managed automatically
      password: "abc123"
      roles: # Optional
      - admin
      - editor
      - viewer
